### ISSUE TITLE
Filter by date: submission and publication date

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/nfdi_search_engine#39]
Do we filter by day or year? This is because the time format needs to be pre-processed in metadata and scripts.

![3](https://github.com/user-attachments/assets/85b69d8a-3f15-4643-a7f3-77eecdeb05b9)

**Comment by haesleinhuepf** [comment]
Would it be possible to filter by date range (e.g. in google scholar you can search for publications between 2015 and 2020)?
